package sid.t1.superpeer;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
Definição número das portas
3000 = Interna peers
20xx = PeerX para clientes
21xx = Client registry
*/


public class Server extends javax.swing.JFrame
{
    SuperPeer superPeer;
    /**
     * Creates new form Server
     */
    public Server()
    {
        initComponents();
        try {
            superPeer = new SuperPeer( this );
        } catch (RemoteException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
        setStopped();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareaOutput = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        buttonOutputClear = new javax.swing.JButton();
        labelOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonStart.setText("Iniciar");
        buttonStart.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonStartActionPerformed(evt);
            }
        });

        buttonStop.setText("Parar");
        buttonStop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonStopActionPerformed(evt);
            }
        });

        tareaOutput.setEditable(false);
        tareaOutput.setColumns(20);
        tareaOutput.setRows(5);
        ( ( javax.swing.text.DefaultCaret ) this.tareaOutput.getCaret() ).setUpdatePolicy( javax.swing.text.DefaultCaret.ALWAYS_UPDATE );
        jScrollPane1.setViewportView(tareaOutput);

        buttonOutputClear.setText("Limpar");
        buttonOutputClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOutputClearActionPerformed(evt);
            }
        });

        labelOutput.setText("Saída:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonStop)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOutput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonOutputClear)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStart)
                    .addComponent(buttonStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOutputClear)
                    .addComponent(labelOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonStartActionPerformed
    {//GEN-HEADEREND:event_buttonStartActionPerformed
        superPeer.start();
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonStopActionPerformed
    {//GEN-HEADEREND:event_buttonStopActionPerformed
        superPeer.stop();
    }//GEN-LAST:event_buttonStopActionPerformed

    private void buttonOutputClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOutputClearActionPerformed
    {//GEN-HEADEREND:event_buttonOutputClearActionPerformed
        tareaOutput.setText( "" );
    }//GEN-LAST:event_buttonOutputClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( Server.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( Server.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( Server.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( Server.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new Server().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOutputClear;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelOutput;
    private javax.swing.JTextArea tareaOutput;
    // End of variables declaration//GEN-END:variables
    
    public void setStarted()
    {
        buttonStart.setEnabled( false );
        buttonStop.setEnabled( true );
    }
    
    public void setStopped()
    {
        buttonStart.setEnabled( true );
        buttonStop.setEnabled( false );
    }
    
    // Imprime na área de texto da interface.
    public void println( String message )
    {
        tareaOutput.append( "> " + message + "\n" );
    }
    
    // Mostra uma MessageBox com uma mensagem de erro.
    public void showError( String message )
    {
        javax.swing.JOptionPane.showMessageDialog( this, message, "Error", javax.swing.JOptionPane.ERROR_MESSAGE );
    }
}
